#!/bin/bash
firewall-offline-cmd --zone=public --add-port=80/tcp
systemctl restart firewalld

yum -y install httpd
apachectl start
systemctl enable httpd

usermod -a -G apache opc
chown -R opc:apache /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;
cd /var/www/html

EXTERNAL_IP=$(curl -s -m 10 http://whatismyip.akamai.com/)
LOCAL_IP=$(ip route show to 0.0.0.0/0 | awk '{ print $5 }' | xargs ip addr show | grep -Po 'inet \K[\d.]+')
#HOSTNAME=$(hostname -f)
HOSTNAME=$(hostname)

curl -sL --retry 3 http://169.254.169.254/opc/v1/instance/ | tee /tmp/instance_meta.json
read INSTANCE_ID_0 INSTANCE_ID_1 <<< $(jq -r '.id' /tmp/instance_meta.json | perl -pe 's/(.*?\.){4}\K/ /g' | perl -pe 's/\.+\s/ /g')
INSTANCE_ID=$INSTANCE_ID_0.$INSTANCE_ID_1
echo "Hostname: $HOSTNAME <br>" > index.html
echo "Public IP: $EXTERNAL_IP <br>" >> index.html
echo "Private IP: $LOCAL_IP <br>" >> index.html
echo "Instance ID: $INSTANCE_ID <br>" >> index.html